#!/usr/bin/env python3
"""Copy Graham Factory audio into the Godot project and rebuild the local dialogue index.

Standard library only (works in Termux). This is steps 6-7 of the production workflow in
CLAUDE_INTEGRATION.md: the game never reads generated_audio/ directly and never talks to ElevenLabs.

    python sync_godot.py                      # import whatever exists in generated_audio/
    python sync_godot.py --source ~/storage/downloads/graham   # or another folder of <id>.mp3 files
    python sync_godot.py --approve correct_01 name_aaron        # mark takes as approved for release
    python sync_godot.py --unapprove wrong_01
    python sync_godot.py --check              # report only, change nothing

Index: <repo>/config/graham_voice_index.json
  clips[id] = {path, status: missing|development|approved, text, mood, bytes}
  names[lowercase name] = id        (from manifest ids "name_<x>")
New imports are "development". Only --approve promotes a take; release validation reports any
clip that is not approved. Re-importing a changed file demotes it back to "development".
"""
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import shutil
import sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent.parent
MANIFEST = HERE / "manifest.json"
INDEX = REPO / "config" / "graham_voice_index.json"
ASSET_DIR = REPO / "assets" / "audio" / "graham"
RES_DIR = "res://assets/audio/graham"
EXTS = (".mp3", ".ogg", ".wav")


def sha(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def load_index() -> dict:
    if INDEX.exists():
        return json.loads(INDEX.read_text(encoding="utf-8"))
    return {"version": 1, "clips": {}, "names": {}}


def find_source(src: pathlib.Path, line_id: str) -> pathlib.Path | None:
    for ext in EXTS:
        p = src / (line_id + ext)
        if p.exists() and p.stat().st_size > 0:
            return p
    return None


def build(source: pathlib.Path, approve: list, unapprove: list, check: bool) -> dict:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    old = load_index()
    clips, names, report = {}, {}, []
    for line in manifest["lines"]:
        lid = line["id"]
        prev = old.get("clips", {}).get(lid, {})
        entry = {"path": prev.get("path", ""), "status": prev.get("status", "missing"), "text": line["text"],
                 "mood": line.get("mood", ""), "sha": prev.get("sha", ""), "bytes": prev.get("bytes", 0)}
        src = find_source(source, lid) if source.exists() else None
        if src is not None:
            dest = ASSET_DIR / (lid + src.suffix.lower())
            digest = sha(src)
            if digest != entry["sha"] or not dest.exists():
                if not check:
                    ASSET_DIR.mkdir(parents=True, exist_ok=True)
                    for ext in EXTS:  # one format per id
                        stale = ASSET_DIR / (lid + ext)
                        if stale != dest and stale.exists():
                            stale.unlink()
                    shutil.copyfile(src, dest)
                report.append(f"imported {lid} ({src.name})" + (" — new take, back to development" if entry["status"] == "approved" else ""))
                entry.update(path=f"{RES_DIR}/{dest.name}", status="development", sha=digest, bytes=src.stat().st_size)
        if entry["path"] and not (REPO / entry["path"].replace("res://", "")).exists():
            entry.update(path="", status="missing", sha="", bytes=0)
        if not entry["path"]:
            entry["status"] = "missing"
        if lid in approve:
            if entry["status"] == "missing":
                report.append(f"cannot approve {lid}: no audio imported")
            else:
                entry["status"] = "approved"
        if lid in unapprove and entry["status"] == "approved":
            entry["status"] = "development"
        if line.get("text", "") != prev.get("text", line.get("text", "")) and entry["status"] == "approved":
            entry["status"] = "development"
            report.append(f"{lid}: manifest text changed — take needs re-approval")
        clips[lid] = entry
        if lid.startswith("name_"):
            names[lid[5:].lower()] = lid
    unknown = [i for i in approve + unapprove if i not in clips]
    for i in unknown:
        report.append(f"unknown id {i}")
    index = {
        "version": 1,
        "_comment": "Generated by tools/graham_factory/sync_godot.py from manifest.json. Graham's local authored voice (no runtime cloud TTS). status: missing | development | approved.",
        "clips": clips,
        "names": names,
    }
    counts = {s: sum(1 for c in clips.values() if c["status"] == s) for s in ("approved", "development", "missing")}
    report.append("clips: %d approved, %d development, %d missing (of %d)" % (counts["approved"], counts["development"], counts["missing"], len(clips)))
    if not check:
        INDEX.parent.mkdir(parents=True, exist_ok=True)
        INDEX.write_text(json.dumps(index, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    return {"index": index, "report": report}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--source", default=str(HERE / "generated_audio"), help="folder containing <id>.mp3 files")
    ap.add_argument("--approve", nargs="*", default=[])
    ap.add_argument("--unapprove", nargs="*", default=[])
    ap.add_argument("--check", action="store_true", help="report only")
    a = ap.parse_args(argv)
    r = build(pathlib.Path(a.source).expanduser(), a.approve, a.unapprove, a.check)
    print("\n".join(r["report"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
