#!/usr/bin/env python3
"""
Imports the Graham low-budget pack (references/graham/, masters untouched) into runtime assets (D021):

  assets/graham/stills/<state>.png         full-frame 960x720 camera plates (lossy WebP in the pack)
  assets/graham/speech/speech_0N.png       crude speech-cycle bridge frames
  assets/graham/cutouts/<state>.png        RGBA cut-outs for the 3D wide-shot billboard (GrabCut)
  assets/graham/motion/<name>/NNN.jpg      short frame sequences from the zero-cost motion excerpts
  config/graham_states.json                runtime semantic state map (res:// paths, fallbacks)

    python3 tools/art/import_graham.py
Re-run whenever the pack changes. Never edits or downsizes the masters.
"""
import json
import os
import shutil

import cv2
import numpy as np

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
PACK = os.path.join(ROOT, "references", "graham")
OUT = os.path.join(ROOT, "assets", "graham")
LOSSY = '[remap]\n\nimporter="texture"\ntype="CompressedTexture2D"\n\n[params]\n\ncompress/mode=1\ncompress/lossy_quality=%s\nmipmaps/generate=false\n'


def write_import(path, quality="0.9"):
    open(path + ".import", "w").write(LOSSY % quality)


def frames(src_mp4, dst_dir, fps=12.5, size=(960, 720)):
    os.makedirs(dst_dir, exist_ok=True)
    cap = cv2.VideoCapture(src_mp4)
    src_fps = cap.get(cv2.CAP_PROP_FPS) or 25.0
    step = src_fps / fps
    i, n, nxt = 0, 0, 0.0
    while True:
        ok, f = cap.read()
        if not ok:
            break
        if i >= nxt - 1e-6:
            f = cv2.resize(f, size, interpolation=cv2.INTER_AREA)
            p = os.path.join(dst_dir, "%03d.jpg" % n)
            cv2.imwrite(p, f, [cv2.IMWRITE_JPEG_QUALITY, 82])
            write_import(p, "0.85")
            n += 1
            nxt += step
        i += 1
    return n


def main():
    pack_states = json.load(open(os.path.join(PACK, "config", "graham_states.json")))
    profile = json.load(open(os.path.join(PACK, "config", "graham_animation_profile.json")))
    for d in ("stills", "speech", "cutouts", "motion"):
        os.makedirs(os.path.join(OUT, d), exist_ok=True)
    runtime = {"version": 1, "_comment": "Generated by tools/art/import_graham.py from references/graham/config/graham_states.json. Semantic Graham states -> runtime assets + fallbacks (D021). Edit the pack config, then re-run the importer.",
               "canonical_reference": "references/graham/" + pack_states["canonical_reference"],
               "default_state": pack_states["default_state"], "states": {}, "motion": {}, "profile": profile}
    for sid, st in pack_states["states"].items():
        entry = {k: v for k, v in st.items() if k not in ("asset", "speech_cycle")}
        if st.get("asset"):
            src = os.path.join(PACK, st["asset"])
            dst = os.path.join(OUT, "stills", sid + ".png")
            shutil.copyfile(src, dst)
            write_import(dst)
            entry["asset"] = "res://assets/graham/stills/%s.png" % sid
        else:
            entry["asset"] = None
        if st.get("speech_cycle"):
            entry["speech_cycle"] = []
            for p in st["speech_cycle"]:
                dst = os.path.join(OUT, "speech", os.path.basename(p))
                shutil.copyfile(os.path.join(PACK, p), dst)
                write_import(dst)
                entry["speech_cycle"].append("res://assets/graham/speech/" + os.path.basename(p))
        runtime["states"][sid] = entry
    # NOTE: automatic GrabCut cut-outs for a 3D wide-shot billboard were evaluated and rejected
    # (set lettering/props leak in). Wide shots frame the contestant side instead; a clean alpha
    # cut-out is on references/graham/docs/GRAHAM_MISSING_ASSETS.md territory (D022).
    # motion excerpts -> short frame sequences (no runtime video decoding dependency)
    for name, rel in pack_states.get("motion_reference_only", {}).items():
        n = frames(os.path.join(PACK, rel), os.path.join(OUT, "motion", name))
        runtime["motion"][name] = {"dir": "res://assets/graham/motion/%s" % name, "frames": n, "fps": 12.5,
                                   "source": "references/graham/" + rel}
    json.dump(runtime, open(os.path.join(ROOT, "config", "graham_states.json"), "w"), indent=1)
    print("states", len(runtime["states"]), "motion", {k: v["frames"] for k, v in runtime["motion"].items()})


if __name__ == "__main__":
    main()
